"""ajout_colonnes_enfants_et_caf

Revision ID: 099c45b81154
Revises: 
Create Date: 2026-04-13 11:57:55.008257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099c45b81154'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance', sa.Column('quotient_caf', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nb_enfants')
    op.drop_column('finance', 'quotient_caf')
    # ### end Alembic commands ###
