services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    container_name: atlas_api
    ports:
      - "9000:9000"
    volumes:
      - ./logs:/app/logs
      - ./main.py:/app/main.py
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: atlas_streamlit
    environment:
      - API_URL=http://api:9000
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./app.py:/app/app.py
    depends_on:
      - api
    restart: always
